services:
  sample-rails-react-crud-client:
    container_name: sample-crud-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8000:8000
  sample-rails-react-crud-server:
    container_name: sample-crud-server
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      