services:
  client:
    container_name: sample-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8000:8000
  server:
    container_name: sample-server
    build:
      context: ../sample-rails-react-crud-server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      